athena:
  target: dev
  outputs:
    dev:
      type: postgres
      host: 192.168.124.160
      user: postgres
      password: postgres015@@
      port: 5433
      dbname: postgres
      schema: public
      threads: 4