version: 2

sources:
  - name: cripto_data
    database: postgres
    schema: raw_crypto_data

    tables:
      - name: crypto_data
        description: "Tabela que contém informações das transacoes de cripto na bolsa em dolar."

        columns:
          - name: id
            description: "Identificador único da transação."
            tests:
              - not_null
          - name: ath
            description: "All Time High."
          - name: atl
            description: "All Time Low."
          - name: roi
            description: "Return on Investment."
          - name: name
            description: "Nome da cripto."
          - name: image
            description: "Imagem da cripto."
          - name: symbol
            description: "Símbolo da cripto."
          - name: low_24h
            description: "Menor valor em 24 horas."
          - name: ath_date
            description: "Data do All Time High."
          - name: atl_date
            description: "Data do All Time Low."
          - name: high_24h
            description: "Maior valor em 24 horas."
          - name: market_cap
            description: "Capitalização de mercado."
          - name: max_supply
            description: "Suprimento máximo."
          - name: last_updated
            description:  "Última atualização."
          - name: total_supply
            description: "Suprimento total."
          - name: total_volume
            description: "Volume total."
          - name: current_price
            description: "Preço atual."
          - name: market_cap_rank
            description: "Ranking de capitalização de mercado."
          - name: price_change_24h
            description: "Mudança de preço em 24 horas."
          - name: circulating_supply
            description: "Suprimento circulante."
          - name: ath_change_percentage
            description: "Porcentagem de mudança do All Time High."
          - name: atl_change_percentage
            description: "Porcentagem de mudança do All Time Low."
          - name: market_cap_change_24h
            description: "Mudança de capitalização de mercado em 24 horas."
          - name: fully_diluted_valuation
            description: "Avaliação totalmente diluída."
          - name: price_change_percentage_24h
            description: "Porcentagem de mudança de preço em 24 horas."
          - name: market_cap_change_percentage_24h
            description: "Porcentagem de mudança de capitalização de mercado em 24 horas."
          - name: _airbyte_raw_id
            description: "Identificador único da transação."
          - name: _airbyte_extracted_at
            description: "Data de extração."
          - name: _airbyte_generation_id
            description: "Identificador de geração."
          - name: _airbyte_meta
            description: "Metadados."