athena:
  target: dev
  outputs:
    dev:
      type: postgres
      host: "{{ env_var('DBT_HOST') }}"
      user: "{{ env_var('DBT_USER') }}"
      password: "{{ env_var('DBT_PASSWORD') }}"
      port: "{{ env_var('DBT_PORT', default='5432') }}"  # Pode definir um valor padrão caso a variável não seja definida
      dbname: "{{ env_var('DBT_DBNAME', default='postgres') }}"
      schema: "{{ env_var('DBT_SCHEMA', default='public') }}"
      threads: 4
