athena:
  target: dev
  outputs:
    dev:
      type: postgres
      host: "{{ env_var('DBT_HOST') }}"
      user: "{{ env_var('DBT_USER') }}"
      password: "{{ env_var('DBT_PASS') }}"
      port: 5433
      dbname: "{{ env_var('DBT_DBNAME', default='postgres') }}"
      schema: "{{ env_var('DBT_SCHEMA', default='public') }}"
      threads: 4
